//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductInterfaces
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        public int ID { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DeadLine { get; set; }
        public Nullable<int> EstimationTime { get; set; }
        public Nullable<bool> Finnished { get; set; }
    }
}
